import { EventItem, StudentProfile } from './types';

export const MOCK_EVENTS: EventItem[] = [
  {
    id: 'allcollege-grand-hackathon-2026',
    title: 'National Collegiate Grand Offline Hackathon 2026',
    organizer: {
      name: 'AllCollegeEvent.com & Premier Tech Campus',
      college: 'National Institute of Technology & Tech Campus',
      verified: true,
      logoUrl: '🏆',
    },
    type: 'Hackathon',
    category: 'AI & Machine Learning',
    mode: 'Offline',
    location: 'Hyderabad, India (Flagship Campus Arena)',
    startDate: '2026-10-15',
    endDate: '2026-10-17',
    duration: '36 Hours Non-Stop',
    deadline: '2026-10-01',
    description: 'The flagship annual 36-hour offline collegiate hackathon bringing together 1,500+ top student innovators across the country. Tracks include Generative AI & Autonomous Agents, Healthcare Intelligence, Smart Mobility & IoT, and Web3 Decentralized Systems. Features direct on-spot hiring interviews by tier-1 tech firms, 1:1 venture mentorship, and national media coverage.',
    shortSummary: 'National flagship 36-hour offline hackathon focusing on AI, autonomous agents, and next-gen tech with ₹5,00,000+ prize pool.',
    prizePool: '₹5,00,000 + VC Funding & Cloud Credits',
    perks: ['Direct Fast-track Interviews', '₹5 Lakh Cash Prize', 'Google & AWS Cloud Credits', 'Accommodation & Food Included', 'Physical Medals & Goodies'],
    eligibility: ['B.Tech / B.E / M.Tech / MCA (All Years)', 'Teams of 2 to 4 members', 'Valid College ID Required'],
    requiredSkills: ['Python', 'Machine Learning', 'API Development', 'Git', 'Problem Solving'],
    skillsGained: ['Autonomous AI Agents', 'Fullstack AI Deployment', 'Team Leadership', 'Real-world Pitching', 'Production MLOps'],
    difficulty: 'Elite Championship',
    targetAudience: ['Pre-final & Final Year CS/IT/AI/ECE Students', 'Hackathon Enthusiasts', 'Aspiring Founders'],
    careerRelevance: ['AI/ML Engineer', 'Founding Engineer', 'Fullstack AI Developer', 'Product Architect'],
    trustScore: 99,
    trustFactors: {
      organizerReputation: 98,
      curriculumDepth: 100,
      prizeVerification: 100,
      mentorshipQuality: 98,
    },
    featured: true,
    registrationCount: 1240,
    maxCapacity: 1500,
    syllabus: [
      { module: 'Phase 1: Idea Pitch & Architecture Defense', details: 'Present problem formulation and system architecture to jury of industry tech leads.' },
      { module: 'Phase 2: Midnight Sprint & Mentor Checkpoint', details: 'Deep coding session with 1:1 architecture review by senior engineers.' },
      { module: 'Phase 3: Final Demo & Grand Stage Pitching', details: 'Top 10 teams pitch on main stage before VC panel and industry hiring directors.' }
    ],
    mentors: [
      { name: 'Dr. Ramesh Sundaram', role: 'Chief AI Scientist', company: 'DeepMind Research Fellow' },
      { name: 'Meera Nambiar', role: 'VP of Engineering', company: 'AI Scalability Ecosystem' },
      { name: 'Aditya Kulkarni', role: 'Partner & Angel Investor', company: 'Tech Innovation Capital' }
    ]
  },
  {
    id: 'ai-vision-summit-2026',
    title: 'NeurAI 2026: Deep Learning & Computer Vision Research Summit',
    organizer: {
      name: 'IEEE Computational Intelligence Society',
      college: 'IIT Madras Research Park',
      verified: true,
      logoUrl: '🧠',
    },
    type: 'Conference',
    category: 'AI & Machine Learning',
    mode: 'Hybrid',
    location: 'Chennai, India & Virtual Stream',
    startDate: '2026-11-05',
    endDate: '2026-11-07',
    duration: '3 Days',
    deadline: '2026-10-20',
    description: 'Premier research conference presenting cutting-edge breakthroughs in Multimodal LLMs, Vision-Language-Action (VLA) models, Diffusion Architectures, and Neuromorphic Computing. Selected student research papers receive IEEE Xplore publication and travel grants.',
    shortSummary: 'Premier research symposium on multimodal deep learning with IEEE publication tracks and international keynote speakers.',
    prizePool: '₹2,00,000 Research Grant & IEEE Publication',
    perks: ['IEEE Paper Indexing', 'Research Mentorship', 'Travel Subsidy for Presenters', 'Access to NVIDIA DGX Compute'],
    eligibility: ['Undergrad / Postgrad Students & Researchers', 'Interest in Computer Vision & Transformers'],
    requiredSkills: ['PyTorch', 'Linear Algebra', 'Computer Vision Basics', 'Python'],
    skillsGained: ['Multimodal Transformers', 'Diffusion Models', 'Scientific Paper Writing', 'CUDA Acceleration'],
    difficulty: 'Advanced',
    targetAudience: ['CSE / Data Science Students', 'Prospective Masters/PhD Applicants', 'AI Researchers'],
    careerRelevance: ['AI Research Scientist', 'Computer Vision Specialist', 'Deep Learning Engineer'],
    trustScore: 97,
    trustFactors: {
      organizerReputation: 99,
      curriculumDepth: 98,
      prizeVerification: 95,
      mentorshipQuality: 96,
    },
    featured: true,
    registrationCount: 680,
    maxCapacity: 800,
    syllabus: [
      { module: 'Keynote 1: Next Horizon in Multimodal Reasoning', details: 'Exploring zero-shot video comprehension and spatial reasoning engines.' },
      { module: 'Hands-on Lab: Fine-tuning Open Weights with LoRA & vLLM', details: 'Interactive GPU cluster lab optimizing 70B parameter models on consumer hardware.' },
      { module: 'Student Oral Presentations & Poster Defense', details: 'Peer-reviewed sessions evaluated by IEEE Fellows.' }
    ]
  },
  {
    id: 'cloud-native-devops-bootcamp',
    title: 'Zero to Production: Kubernetes, Terraform & Cloud Architecture Bootcamp',
    organizer: {
      name: 'Cloud Native Computing Community (CNCF Student Chapter)',
      college: 'BITS Pilani',
      verified: true,
      logoUrl: '☁️',
    },
    type: 'Bootcamp',
    category: 'Cloud & DevOps',
    mode: 'Virtual',
    location: 'Live Interactive Virtual Labs',
    startDate: '2026-09-20',
    endDate: '2026-10-04',
    duration: '2 Weeks (Weekend Intensive)',
    deadline: '2026-09-18',
    description: 'Intensive 2-week hands-on bootcamp taking students from container fundamentals to automated GitOps CI/CD pipelines, multi-region Kubernetes clusters, Prometheus/Grafana observability, and Terraform Infrastructure as Code.',
    shortSummary: 'Hands-on cloud engineering mastery program covering K8s, Helm, Terraform, and production GitOps with real cloud sandbox credits.',
    prizePool: 'Free CKA/CKAD Exam Vouchers (Worth ₹30,000 each)',
    perks: ['Free $150 AWS/GCP Cloud Credits', 'Linux Foundation Certification Vouchers', 'Verified Digital Badge', 'Resume Review by SREs'],
    eligibility: ['Open to All Branches (2nd to 4th Year)', 'Basic Linux CLI familiarity required'],
    requiredSkills: ['Linux CLI', 'Docker Basics', 'Networking Fundamentals'],
    skillsGained: ['Kubernetes (K8s)', 'Terraform (IaC)', 'GitHub Actions CI/CD', 'Prometheus & Grafana', 'ArgoCD'],
    difficulty: 'Intermediate',
    targetAudience: ['DevOps Enthusiasts', 'Backend Developers', 'Cloud Solutions Aspirants'],
    careerRelevance: ['Site Reliability Engineer (SRE)', 'Cloud Architect', 'DevOps Specialist', 'Infrastructure Engineer'],
    trustScore: 94,
    trustFactors: {
      organizerReputation: 95,
      curriculumDepth: 96,
      prizeVerification: 92,
      mentorshipQuality: 93,
    },
    registrationCount: 920,
    maxCapacity: 1000
  },
  {
    id: 'data-analytics-quant-challenge',
    title: 'AlphaQuant 2026: Algorithmic Trading & Predictive Analytics Challenge',
    organizer: {
      name: 'Department of Data Science & Economics',
      college: 'IIT Delhi',
      verified: true,
      logoUrl: '📈',
    },
    type: 'Competition',
    category: 'Data Science & Analytics',
    mode: 'Virtual',
    location: 'QuantConnect Platform (Online)',
    startDate: '2026-10-08',
    endDate: '2026-10-14',
    duration: '7 Days',
    deadline: '2026-10-05',
    description: 'Develop high-frequency statistical arbitrage and NLP sentiment trading strategies using real tick-level stock and crypto market datasets. Backtest models against historical stress periods and run live paper trading execution.',
    shortSummary: 'Competitive quantitative finance challenge analyzing live market feeds to build automated trading alphas with hedge fund internships.',
    prizePool: '₹3,50,000 + Quant Hedge Fund Summer Internships',
    perks: ['Direct Summer Internship Offers', 'High-speed Tick Data Access', 'Wall Street / Dalal Street Mentor Feedback'],
    eligibility: ['Students passionate about Statistics, ML, and Finance'],
    requiredSkills: ['Python', 'Pandas & NumPy', 'Time Series Analysis', 'Statistics'],
    skillsGained: ['Backtesting Frameworks', 'Portfolio Risk Optimization', 'Feature Engineering', 'Market Microstructure'],
    difficulty: 'Advanced',
    targetAudience: ['Data Science / Math / CS / Finance Students', 'Competitive Coders'],
    careerRelevance: ['Quantitative Analyst (Quant)', 'Data Scientist', 'Financial ML Engineer', 'Risk Modeler'],
    trustScore: 96,
    trustFactors: {
      organizerReputation: 98,
      curriculumDepth: 95,
      prizeVerification: 98,
      mentorshipQuality: 93,
    },
    registrationCount: 450,
    maxCapacity: 600
  },
  {
    id: 'robotics-ros2-autonomous-cup',
    title: 'RoboQuest 2026: ROS2 Autonomous Drone & Rover Championship',
    organizer: {
      name: 'Robotics & Automation Society',
      college: 'NIT Trichy',
      verified: true,
      logoUrl: '🤖',
    },
    type: 'Competition',
    category: 'Robotics & IoT',
    mode: 'Offline',
    location: 'Tiruchirappalli, Tamil Nadu (NIT Trichy Arena)',
    startDate: '2026-11-12',
    endDate: '2026-11-14',
    duration: '3 Days',
    deadline: '2026-10-25',
    description: 'National offline robotics arena competition where autonomous rovers and micro-UAVs navigate GPS-denied obstacle courses using SLAM, LiDAR point clouds, and Jetson Orin edge computing.',
    shortSummary: 'National autonomous robotics grand prix featuring LiDAR navigation, obstacle avoidance, and edge AI on physical track arenas.',
    prizePool: '₹2,50,000 + NVIDIA Jetson Orin Developer Kits',
    perks: ['Hardware Kits Provided', 'Robotics Hardware Exhibition', 'Aero & Defence Industry Recruitment'],
    eligibility: ['ECE / EEE / Mech / Mechatronics / CSE Students', 'Teams of 3 to 5'],
    requiredSkills: ['C++', 'ROS2 / Gazebo Basics', 'Microcontrollers (ESP32/STM32)', 'Control Systems'],
    skillsGained: ['Simultaneous Localization and Mapping (SLAM)', 'Edge AI on Jetson', 'Sensor Fusion (IMU + LiDAR)', 'Embedded Linux'],
    difficulty: 'Advanced',
    targetAudience: ['Robotics Enthusiasts', 'Embedded Engineers', 'Hardware Hackers'],
    careerRelevance: ['Autonomous Systems Engineer', 'Robotics Software Engineer', 'Embedded Systems Architect'],
    trustScore: 95,
    trustFactors: {
      organizerReputation: 96,
      curriculumDepth: 97,
      prizeVerification: 94,
      mentorshipQuality: 93,
    },
    registrationCount: 310,
    maxCapacity: 400
  },
  {
    id: 'fullstack-web3-defi-hackathon',
    title: 'DecentralHacks 2026: Next-Gen Web3 & Decentralized Intelligence',
    organizer: {
      name: 'Ethereum & Solana Student Collective',
      college: 'IIIT Hyderabad',
      verified: true,
      logoUrl: '⚡',
    },
    type: 'Hackathon',
    category: 'Full Stack & Web3',
    mode: 'Hybrid',
    location: 'Hyderabad, India + Worldwide Discord',
    startDate: '2026-09-28',
    endDate: '2026-09-30',
    duration: '48 Hours',
    deadline: '2026-09-24',
    description: 'Build user-friendly Web3 protocols, Zero-Knowledge identity systems, and decentralized AI compute marketplaces using Next.js 15, Solidity / Rust, and Account Abstraction.',
    shortSummary: '48-hour global hybrid hackathon targeting smart contracts, ZK-proofs, and modern fullstack dApps with $30k global bounty pool.',
    prizePool: '$30,000 in Grants + Protocol Tokens',
    perks: ['Grant Fast-Tracking', 'Gas Subsidy Vouchers', 'Global VC Demo Day'],
    eligibility: ['All college students and recent grads worldwide'],
    requiredSkills: ['JavaScript / TypeScript', 'React / Next.js', 'Solidity or Rust (Basics)', 'Web3.js / Ethers'],
    skillsGained: ['Smart Contract Security', 'Zero-Knowledge Proofs', 'Account Abstraction', 'IPFS & Decentralized Storage'],
    difficulty: 'Intermediate',
    targetAudience: ['Full Stack Devs', 'Crypto Builders', 'Frontend Engineers'],
    careerRelevance: ['Web3 Fullstack Engineer', 'Smart Contract Auditor', 'Blockchain Developer'],
    trustScore: 92,
    trustFactors: {
      organizerReputation: 93,
      curriculumDepth: 91,
      prizeVerification: 94,
      mentorshipQuality: 90,
    },
    registrationCount: 780,
    maxCapacity: 1200
  },
  {
    id: 'cybersec-national-ctf-2026',
    title: 'CyberShield 2026: Inter-University Red Team / Blue Team CTF',
    organizer: {
      name: 'National Cybersecurity Centre & Dept of CSE',
      college: 'COEP Technological University',
      verified: true,
      logoUrl: '🛡️',
    },
    type: 'Competition',
    category: 'Cybersecurity',
    mode: 'Virtual',
    location: 'CyberRange Live Platform',
    startDate: '2026-10-22',
    endDate: '2026-10-23',
    duration: '24 Hours',
    deadline: '2026-10-18',
    description: '24-hour jeopardy-style and attack-defense Capture The Flag competition. Challenges encompass Binary Exploitation, Web App Vulnerabilities (OWASP Top 10), Reverse Engineering, Cryptography, and Cloud Security Misconfigurations.',
    shortSummary: 'National inter-university CTF challenge spanning binary exploitation, web security, and cloud forensics with defense sector opportunities.',
    prizePool: '₹1,80,000 + Security Research Bounties',
    perks: ['Offensive Security Exam Discounts', 'Direct Interview Calls by Cyber Defence Firms', 'Hall of Fame Badge'],
    eligibility: ['College Students with active interest in Ethical Hacking'],
    requiredSkills: ['Linux', 'Network Protocols (TCP/IP)', 'Python Scripting', 'Web Security Basics'],
    skillsGained: ['Binary Reverse Engineering', 'Kernel Exploitation', 'Digital Forensics & Incident Response', 'Cryptography'],
    difficulty: 'Advanced',
    targetAudience: ['Cybersecurity Enthusiasts', 'InfoSec Researchers', 'Ethical Hackers'],
    careerRelevance: ['Security Analyst', 'Penetration Tester (Ethical Hacker)', 'Cloud Security Engineer'],
    trustScore: 93,
    trustFactors: {
      organizerReputation: 95,
      curriculumDepth: 94,
      prizeVerification: 91,
      mentorshipQuality: 92,
    },
    registrationCount: 510,
    maxCapacity: 750
  },
  {
    id: 'mobile-flutter-ai-bootcamp',
    title: 'Cross-Platform Mobile AI with Flutter & On-Device ML',
    organizer: {
      name: 'Google Developer Student Clubs (GDSC)',
      college: 'VIT Vellore',
      verified: true,
      logoUrl: '📱',
    },
    type: 'Workshop',
    category: 'Mobile & App Dev',
    mode: 'Hybrid',
    location: 'VIT Vellore & YouTube Live Stream',
    startDate: '2026-10-02',
    endDate: '2026-10-03',
    duration: '2 Days (Hands-on)',
    deadline: '2026-09-30',
    description: 'Build polished, responsive iOS and Android apps using Flutter 3, Riverpod state management, and integrate lightweight on-device Gemini Nano & MediaPipe models for real-time offline AI inference.',
    shortSummary: '2-day intensive hands-on workshop building production cross-platform apps with on-device machine learning and clean architecture.',
    prizePool: '₹50,000 App Showcase Challenge',
    perks: ['Certificate from GDSC', 'Play Store Publishing Credits', 'App Code Templates'],
    eligibility: ['Open to all students interested in Mobile Development'],
    requiredSkills: ['Dart Basics', 'Object Oriented Programming', 'Mobile UI Concepts', 'Flutter'],
    skillsGained: ['Flutter UI & Animation', 'State Management (Riverpod)', 'MediaPipe Vision Integration', 'RESTful API consumption'],
    difficulty: 'Beginner',
    targetAudience: ['Aspiring Mobile Developers', 'Frontend Engineers', 'Product Creators'],
    careerRelevance: ['Mobile Application Developer (Flutter/iOS/Android)', 'Frontend Mobile Specialist'],
    trustScore: 91,
    trustFactors: {
      organizerReputation: 94,
      curriculumDepth: 89,
      prizeVerification: 90,
      mentorshipQuality: 91,
    },
    registrationCount: 840,
    maxCapacity: 1000
  },
  {
    id: 'bengaluru-ai-hackfest-2026',
    title: 'Bengaluru AI Agents & LLMOps Hackfest 2026',
    organizer: {
      name: 'Bengaluru Tech Innovation Alliance',
      college: 'IISc Bangalore Tech Hub',
      verified: true,
      logoUrl: '⚡',
    },
    type: 'Hackathon',
    category: 'AI & Machine Learning',
    mode: 'Offline',
    location: 'Bengaluru (Koramangala Tech Campus)',
    startDate: '2026-11-05',
    endDate: '2026-11-07',
    duration: '48 Hours',
    deadline: '2026-10-25',
    description: 'Autonomous multi-agent orchestration, function calling, vector retrieval, and scalable LLMOps deployment on GPU clusters. Network directly with Tier-1 AI startups and venture investors.',
    shortSummary: '48-hour flagship AI hackfest in Bengaluru focusing on autonomous LLM agents and enterprise AI.',
    prizePool: '₹4,50,000 + Angel Grants',
    perks: ['₹4.5 Lakh Cash Grants', 'Direct Internship Offers', 'NVIDIA GPU Compute Credits'],
    eligibility: ['College Students & Recent Graduates', 'Teams of 2-4 members'],
    requiredSkills: ['Python', 'LangChain', 'PyTorch', 'FastAPI', 'Vector Databases'],
    skillsGained: ['Agentic Workflows', 'RAG Pipelines', 'MLOps Deployment', 'Production Prompt Engineering'],
    difficulty: 'Advanced',
    targetAudience: ['AI/ML Developers', 'Full Stack AI Builders', 'Data Scientists'],
    careerRelevance: ['AI Engineer', 'LLM Systems Architect', 'Machine Learning Researcher'],
    trustScore: 98,
    trustFactors: {
      organizerReputation: 99,
      curriculumDepth: 97,
      prizeVerification: 98,
      mentorshipQuality: 98,
    },
    registrationCount: 1120,
    maxCapacity: 1500
  },
  {
    id: 'chennai-web3-defi-summit',
    title: 'Chennai Blockchain & Smart Contracts Summit 2026',
    organizer: {
      name: 'Ethereum Student Developers Guild',
      college: 'IIT Madras Shaastra Labs',
      verified: true,
      logoUrl: '💎',
    },
    type: 'Hackathon',
    category: 'Full Stack & Web3',
    mode: 'Offline',
    location: 'Chennai (IIT Madras Research Arena)',
    startDate: '2026-10-28',
    endDate: '2026-10-30',
    duration: '36 Hours',
    deadline: '2026-10-20',
    description: 'Build high-performance decentralized finance, zero-knowledge proofs, and consumer decentralized applications on Ethereum Layer 2s and Solana.',
    shortSummary: 'Premier 36-hour Web3 hackathon in Chennai with ₹3,00,000 prize pool and protocol bounties.',
    prizePool: '₹3,00,000 + $10,000 Protocol Bounties',
    perks: ['Protocol Grants', 'Web3 Foundation Certificates', 'Incubation Support'],
    eligibility: ['Engineering Students interested in Blockchain & Cryptography'],
    requiredSkills: ['Solidity', 'Rust', 'TypeScript', 'Ethers.js', 'Next.js'],
    skillsGained: ['Smart Contract Security', 'ZK Proofs', 'DeFi Liquidity Protocols', 'Gas Optimization'],
    difficulty: 'Advanced',
    targetAudience: ['Web3 Developers', 'Cryptography Enthusiasts', 'Full Stack Engineers'],
    careerRelevance: ['Blockchain Developer', 'Smart Contract Auditor', 'Full Stack Web3 Architect'],
    trustScore: 96,
    trustFactors: {
      organizerReputation: 97,
      curriculumDepth: 95,
      prizeVerification: 96,
      mentorshipQuality: 96,
    },
    registrationCount: 650,
    maxCapacity: 900
  },
  {
    id: 'mumbai-fintech-quant-challenge',
    title: 'Mumbai Algorithmic Trading & High-Frequency FinTech Cup',
    organizer: {
      name: 'IIT Bombay E-Cell & Finance Club',
      college: 'IIT Bombay Powai Campus',
      verified: true,
      logoUrl: '📈',
    },
    type: 'Competition',
    category: 'FinTech & Algorithmic Trading',
    mode: 'Hybrid',
    location: 'Mumbai (IIT Bombay Campus & Online Simulator)',
    startDate: '2026-11-12',
    endDate: '2026-11-14',
    duration: '3 Days',
    deadline: '2026-11-01',
    description: 'Develop low-latency statistical arbitrage models, order book simulations, and algorithmic execution bots against real-time simulated market feeds.',
    shortSummary: 'National quantitative finance and algorithmic trading challenge with direct hedge fund interview calls.',
    prizePool: '₹3,50,000 + Quant Desk Interviews',
    perks: ['Direct Interviews with Quant Funds', 'Cash Prizes', 'Bloomberg Terminal Access'],
    eligibility: ['Open to all engineering, mathematics, and finance undergraduates'],
    requiredSkills: ['Python', 'C++', 'Pandas', 'NumPy', 'Probability & Statistics'],
    skillsGained: ['Quantitative Modeling', 'Risk Analysis', 'Low-Latency Architecture', 'Financial Econometrics'],
    difficulty: 'Elite Championship',
    targetAudience: ['Aspiring Quants', 'Competitive Programmers', 'Math & CS Majors'],
    careerRelevance: ['Quantitative Researcher', 'Algorithmic Trader', 'Financial Software Engineer'],
    trustScore: 97,
    trustFactors: {
      organizerReputation: 98,
      curriculumDepth: 96,
      prizeVerification: 97,
      mentorshipQuality: 97,
    },
    registrationCount: 890,
    maxCapacity: 1200
  },
  {
    id: 'delhi-cloud-kubernetes-championship',
    title: 'Delhi-NCR Cloud Native & Kubernetes Championship',
    organizer: {
      name: 'Cloud Native Computing Foundation (CNCF Student Chapter)',
      college: 'DTU Delhi (Delhi Technological University)',
      verified: true,
      logoUrl: '☁️',
    },
    type: 'Hackathon',
    category: 'Cloud & DevOps',
    mode: 'Offline',
    location: 'Delhi NCR (DTU Auditorium)',
    startDate: '2026-11-18',
    endDate: '2026-11-20',
    duration: '36 Hours',
    deadline: '2026-11-10',
    description: 'Design and deploy resilient, multi-region Kubernetes clusters, GitOps pipelines with ArgoCD, and automated chaos engineering experiments on AWS and Azure.',
    shortSummary: '36-hour DevOps and Cloud Infrastructure hackathon with AWS cloud credits and enterprise hiring passes.',
    prizePool: '₹2,50,000 + AWS Cloud Grants',
    perks: ['AWS Certification Vouchers', 'CKA Exam Discounts', '₹2.5 Lakh Cash Awards'],
    eligibility: ['College Students across CS, IT, and Cloud disciplines'],
    requiredSkills: ['Linux', 'Docker', 'Kubernetes', 'CI/CD', 'Terraform'],
    skillsGained: ['Production Cluster Management', 'GitOps Infrastructure', 'Observability (Prometheus/Grafana)', 'Site Reliability Engineering'],
    difficulty: 'Intermediate',
    targetAudience: ['DevOps Enthusiasts', 'Cloud Engineers', 'Backend Architects'],
    careerRelevance: ['DevOps Engineer', 'Cloud Architect', 'Site Reliability Engineer (SRE)'],
    trustScore: 95,
    trustFactors: {
      organizerReputation: 96,
      curriculumDepth: 94,
      prizeVerification: 95,
      mentorshipQuality: 95,
    },
    registrationCount: 780,
    maxCapacity: 1000
  },
  {
    id: 'pune-robotics-drone-symposium',
    title: 'Pune Autonomous Aerial Drones & Robotics Grand Prix',
    organizer: {
      name: 'Robotics Society of India',
      college: 'COEP Technological University Pune',
      verified: true,
      logoUrl: '🤖',
    },
    type: 'Competition',
    category: 'Robotics & IoT',
    mode: 'Offline',
    location: 'Pune (COEP Arena Ground)',
    startDate: '2026-12-02',
    endDate: '2026-12-04',
    duration: '3 Days',
    deadline: '2026-11-20',
    description: 'Build autonomous quadcopters equipped with onboard optical flow cameras and LiDAR sensors to navigate complex indoor obstacle courses autonomously.',
    shortSummary: 'Premier autonomous drone and robotics obstacle navigation championship in Pune with ₹3,00,000 prize pool.',
    prizePool: '₹3,00,000 + Drone Hardware Kits',
    perks: ['Hardware Sponsorships', 'Physical Trophies & Medals', 'Aerospace Mentorship'],
    eligibility: ['Teams of 2-5 students with working autonomous UAV/Robot hardware'],
    requiredSkills: ['C++', 'Python', 'ROS2', 'OpenCV', 'Embedded Systems'],
    skillsGained: ['Visual SLAM', 'Trajectory Optimization', 'Sensor Fusion', 'Motor Control Tuning'],
    difficulty: 'Elite Championship',
    targetAudience: ['Robotics Enthusiasts', 'Mechatronics & ECE Students', 'Autonomous Systems Builders'],
    careerRelevance: ['Robotics Engineer', 'Autonomous Systems Specialist', 'Embedded Firmware Developer'],
    trustScore: 96,
    trustFactors: {
      organizerReputation: 97,
      curriculumDepth: 96,
      prizeVerification: 95,
      mentorshipQuality: 96,
    },
    registrationCount: 420,
    maxCapacity: 600
  }
];

export const MOCK_STUDENTS: StudentProfile[] = [
  {
    id: 'priya-sharma-cs',
    name: 'Priya Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'priya.s@student.college.ac.in',
    college: 'National Institute of Technology',
    department: 'Computer Science & Engineering (AI & ML)',
    yearOfStudy: 3,
    cgpa: 8.9,
    location: 'Hyderabad, India',
    skills: [
      { name: 'Python', level: 'Expert', score: 92 },
      { name: 'Machine Learning', level: 'Intermediate', score: 78 },
      { name: 'PyTorch', level: 'Intermediate', score: 72 },
      { name: 'API Development', level: 'Intermediate', score: 65 },
      { name: 'Git', level: 'Intermediate', score: 80 }
    ],
    interests: ['Generative AI', 'Multimodal LLMs', 'Hackathons', 'Computer Vision'],
    careerGoals: ['AI/ML Engineer', 'Founding AI Engineer', 'Deep Learning Researcher'],
    targetCompanies: ['Top Tech Firms', 'AI Research Labs'],
    preferredMode: 'All',
    previousEvents: [
      {
        eventId: 'national-sprint-2025',
        eventTitle: 'National Smart AI Sprint 2025',
        category: 'AI & Machine Learning',
        role: 'Team Lead & ML Modeler',
        outcome: 'Top 5 Finalist'
      }
    ],
    bookmarkedEventIds: ['allcollege-grand-hackathon-2026', 'ai-vision-summit-2026'],
    registeredEventIds: ['allcollege-grand-hackathon-2026']
  }
];
